name = "EUPower"
uuid = "560407f1-7869-480b-bd82-9ac58c04aefe"
authors = ["Tamás Borbáth"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
